### ISSUE TITLE
Not able to run. Import problem

### ISSUE THREAD

**Issue by rjalexa** [paradoxxxzero/annealation#1]
Running pnpm install
Lockfile is up to date, resolution step is skipped
Already up to date

> @ prepare /Volumes/2TBWDB/code/annealation
> mkdir -p wasm/pkg

Done in 503ms

Running pnpm start

> @ start /Volumes/2TBWDB/code/annealation
> snowpack dev

[15:40:10] [snowpack] Welcome to Snowpack! Because this is your first time running
this project, Snowpack needs to prepare your dependencies. This is a one-time step
and the results will be cached for the lifetime of your project. Please wait...
[15:40:10] [snowpack] Package "three" exists but package.json "exports" does not include entry for "./examples/jsm/controls/OrbitControls.js".
 ELIFECYCLE  Command failed with exit code 1.
 
 Sorry I hope this is not due to my very limited JS skills.
 
 This program of yours is one of the coolest things I've ever seen :)

BTW would it be possible to have an option to keep the "large star" fixed in the middle of the window?

Thank you very much.

**Comment by paradoxxxzero** [comment]
Hi thanks!

I migrated the build system to vite, can you try again?
(run install -> wasm -> dev or build)

> BTW would it be possible to have an option to keep the "large star" fixed in the middle of the window?

Yeah it sure could be possible with some hacks :)

**Comment by rjalexa** [comment]
I had actually managed to get it running after a number of changes mostly related to mew releases. Now in bed with COVID but will try the vite based build ASAP. This thing you've done is super super cool! Thanks

**Comment by rjalexa** [comment]
Ok so on a new machine I had to install rust, then install wasm, then run wasm-pack build ./wasm --target web and then pnpm install and pnpm run dev

**Comment by paradoxxxzero** [comment]
Thanks , get well soon!

**Comment by rjalexa** [comment]
BTW I stumbled on your fascinating application as I was searching for a 3-body animation. This is ok-ish but not spectacular as yours :) https://www.youtube.com/watch?v=D2YhKaANbWE this other is somewhat nicer but damn the horrible music :) https://www.youtube.com/watch?v=cev3g826iIQ

What I would REALLY love to see is this -> https://www.reddit.com/r/interestingasfuck/comments/1f60cvq/there_is_no_general_closedform_solution_to_the/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button
